app:
  run_mode: "debug"
  name: "onepacd"
log:
  out_path: ./log_output
  max_size: 1024
  max_backups: 30
  max_age: 14
  compress: true
  console_log: true
record_log:
  out_path: ./record_log_output
  max_size: 1024
  max_backups: 30
  max_age: 14
  compress: true
  console_log: false
mongo:
  uri: ${ONEPACD_MONGODB_SERVER:-mongodb://localhost:27017}
  database: onepacd
  password:
  healthcheck: 20
postgres:
  username: ${ONEPACD_POSTGRES_USERNAME:-onepacd}
  password: ${ONEPACD_POSTGRES_PASSWORD:-onepacd}
  host: ${ONEPACD_POSTGRES_HOST:-localhost}
  port: ${ONEPACD_POSTGRES_PORT:-5432}
  database: ${ONEPACD_POSTGRES_DBNAME:-onepacd}
redis:
  addr: ${ONEPACD_REDIS_SERVER:-localhost:6379}
  password:
  db: 0
  healthcheck: 10
service:
  webapi:
    http_listen: ":13665"
  gather:
    grpc_servers: 
      - ${ONEPACD_PACTUS_GRPC_SERVER:-localhost:50051}
  chainextract:
    grpc_servers: 
      - ${ONEPACD_PACTUS_GRPC_SERVER:-localhost:50051}
kafka:
  enable: false
  brokers:
    - "localhost:9092"
  consumer_group: "onepacd-group"
  auto_create_topics: true
  default_partitions: 1
  default_replication_factor: 1
  healthcheck: 30
  sasl:
    enabled: false
    mechanism: "PLAIN"
    username: ""
    password: ""